---
title: '2020-03-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## package 

安裝package

```{r}
library(googlesheets4)
library(dplyr)
library(lubridate)
```
## create object
```{r}
a <- 2
a = 2 # = 與 <-同義
```

```{r}
a
```


```{r}
3 -> b
```

```{r}
a+b
```

```{r}
my_108_total_credits <- 15
_108_total_credits <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```


```{r}
`我的年紀` <- 20
my_age <- `我的年紀`
```

```{r}
ls()
```

##Automic vactor

```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```
#67行相當於 c(2,5)

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```
```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```
##Different type
```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1Vector)
typeof(num2Vector)
```
```{r}
char1<-"你好"
char2<-'你好'
char1Vector<-c("你好","How are you?")
```
```{r}
hesaid <- '"今天多了一個確診"'
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

### Atomic
```{r}
complexVector <- c("小名今年歲數", 15)
```

```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <- "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"
ss <- as_sheets_id(`出席狀況表單網址`)
sheets_read(ss,sheet=1)
```
```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/sean76764/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

##logics
```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
# 加總向量內的所有元素值。
sum(logi1)
```

###Extended atomic vector
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```
```{r}
levels(majors10_factor)
as.integer(majors10_factor) 
```

###class conversion
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
stringInteger+2
```
```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2
```

```{r}
char3 <- c("小明","1","3")
as.integer(char3)
```


##Date time
```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```
```{r}
library(lubridate)
```
台北 2020-03-18 13:52:40
```{r}
TPEdatetime <- ymd_hms(" 2020-03-18 13:52:40", tz="Asia/Taipei")
TPEdatetime
class(TPEdatetime)
typeof(TPEdatetime)
as.double(TPEdatetime)
```

葡萄牙 Mar.18, 2020, 05:52:40
```{r}
pgdatetime <- mdy_hms("Mar.18, 2020, 05:52:40", tz="Europe/Lisbon")
pgdatetime
class(pgdatetime)
typeof(pgdatetime)
as.double(TPEdatetime)
as.double(pgdatetime)
```
```{r}
with_tz(TPEdatetime, tzone="UTC")
with_tz(pgdatetime, tzone="UTC")
```
###注意
ymd_hms(..., tz="Asia/Taipei")
with_tz(..., tzone="Asia/Taipei")
```{r}
with_tz(TPEdatetime, tzone="Europe/Paris")
with_tz(pgdatetime, tzone="Europe/Paris")
```

```{r}
ymd_hms("2020-03-04T06:56:29Z")
```
##練習 ##1 2020-03-04T06:56:29Z	##2 2020-03-11 14:16:43	 ##3 2020-03-11 14:34:33

```{r}
studenttime <- c( ymd_hms("2020-03-04T06:56:29Z"),
                  ymd_hms("2020-03-11 14:16:43", tz="Asia/Taipei"),
                  ymd_hms("2020-03-11 14:34:33", tz="Asia/Taipei")
)
```
```{r}
studenttime
```

)
##list
```{r}

```

